version: '0.1'

services:
  db:
    image: arm64v8/postgres:12.9-alpine
    networks:
      - db
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - docker/db/.env
    ports:
      - 5432:5432

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    networks:
      db:
      backend:
    command: |
      /usr/bin/env sh -c "wait-for db:5432 --
        python create_schema.py
        python palantir.py
        python bot.py
      "
    env_file:
      - docker/app/.env
      - docker/db/.env
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - IPYTHONDIR=/app/.ipython

networks:
  db:
    driver: bridge
  backend:
    driver: bridge

volumes:
  pgdata:
    name: lord_of_the_rings_pgdata
    driver: local
